### PR TITLE
feat: support specifying npm registries via .npmrc

### LINKED ISSUE #402: Private npm packages cannot be imported in edge functions: `npm package '@org/package' does not exist.`
# Bug report

Not clear if this is a bug report or feature request; `deno` has added this functionality but I don't understand the implications for the edge runtime and whether this support in `deno` means it should automatically be supported or not.

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Deno now [supports private registries](https://docs.deno.com/runtime/manual/node/private_registries/), but `supabase`'s local `supabase functions serve` does not seem to.

I have a private package in my `package.json`, my editor is happy with the import, and I can run it directly with `Deno` using `deno run --allow-net supabase/functions/auth/index.ts` but when running via `supabase functions serve` and invoking via `curl` I receive output like the following

```
serving the request with /Users/elyobo/src/project/supabase/functions/auth
failed to load 'npm:@org/package': npm package '@org/package' does not exist.
An error has occured
InvalidWorkerCreation: worker boot error failed to load 'npm:@org/package': npm package '@org/package' does not exist.
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:145:15)
    at async Object.handler (file:///root/index.ts:147:22)
    at async respond (ext:sb_core_main_js/js/http.js:163:14) {
  name: "InvalidWorkerCreation"
}
```

## To Reproduce

* Install a private npm package in `package.json`, e.g. `npm i @org/package` where `@org/package` is a private package that you have access to; this may require you to configure your `~/.npmrc` appropriately e.g. [as described in the `deno` docs](https://docs.deno.com/runtime/manual/node/private_registries/).
* import from the package in an edge function
* serve the function locally using `supabase functions serve`
* invoke the function e.g. using `curl`

## Expected behavior

The private npm package should be imported.

## Screenshots

N/A

## System information

- OS: macOS
- Browser (if applies) N/A
- Version of supabase-js: [e.g. 6.0.2]
```
├── @supabase/supabase-js@2.45.1
├── supabase@1.190.0
```
- Version of Node.js: v20.11.1

## Additional context

`deno` added support recently in https://github.com/denoland/deno/issues/16105; when running the function code directly in `deno` I tested with these versions

```
✗ deno --version
deno 1.45.5 (release, aarch64-apple-darwin)
v8 12.7.224.13
typescript 5.5.2
```

I've also tried shifting the relevant `.npmrc` which configures the private registry and access token around from `~/` to `supabase` and `supabase/functions` but with no change in results.

### PR DESCRIPTION
**Pull request by nyannyacha**
## What kind of change does this PR introduce?

Feature

## Description

Add support for importing packages from the private npm registry via `.npmrc`.

Also, the packages imported from these registries are added together during the bundling process, so it shouldn't change existing behavior.

Resolves #402

### CODE REVIEW

**Comment by elyobo** [comment]
Thanks @nyannyacha 🎉

**Comment by nyannyacha** [comment]
I apologize for the delay.😅 The other work is taking longer than I expected, so I decided to prioritize this.
Thanks for your patience!

**Comment by elyobo** [comment]
No need for apologies at all!

**Review by laktek — APPROVED** [review]

**Comment by israpasos** [comment]
@elyobo is this working for you on local? I'm running v.1.65.3 but still getting: 

```
InvalidWorkerCreation: worker boot error: Failed resolving '@...'.
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:139:15)
    at async Object.handler (file:///root/index.ts:156:22)
    at async respond (ext:sb_core_main_js/js/http.js:163:14) {
  name: "InvalidWorkerCreation"
}```

**Comment by elyobo** [comment]
@israpasos thanks for reminding me to revisit this; I had to backport some changes that I'd make locally for the specific private package code that I'd just copied in as a workaround, but after getting them sorted I have... ran into a very similar sounding issue. `deno` type checks and tests run as expected but the edge functions crash.

```
worker boot error: failed to create the graph: npm package '@my/private-package' does not exist.
    at file:///Users/loboyle/src/uplist/supabase/functions/_shared/auth.ts:14:8
worker boot error: failed to create the graph: npm package '@my/private-package' does not exist.
    at file:///Users/loboyle/src/uplist/supabase/functions/_shared/auth.ts:14:8
InvalidWorkerCreation: worker boot error: failed to create the graph: npm package '@my/private-package' does not exist.
    at file:///Users/loboyle/src/uplist/supabase/functions/_shared/auth.ts:14:8
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:139:15)
    at async Object.handler (file:///root/index.ts:156:22)
    at async respond (ext:sb_core_main_js/js/http.js:163:14) {
  name: "InvalidWorkerCreation"
```

I'm running the most recent `supabase`

```
supabase --version
2.0.0
```

**Comment by nyannyacha** [comment]
Hello @israpasos and @elyobo 😁

I think that problem is not a problem with the edge runtime itself, but a problem caused by cli.
@supabase/cli uses docker to perform `deploy` or `serve` commands, but `.npmrc` does not seem to be mounted.

I have confirmed that if you place `.npmrc` in each function folder, it is properly mounted in the docker container and the private npm registry works well.

If you have time, please open this issue with @supabase/cli.

btw, if you guys are commenting on a closed PR, I will not be able to respond quickly to your comments, so please create a new issue next time 🤗

**Comment by elyobo** [comment]
Thanks @nyannyacha, I'll check this out this afternoon and open an issue with `@supabase/cli` as you suggest.

**Comment by nyannyacha** [comment]
@elyobo Thank you!

**Comment by elyobo** [comment]
@nyannyacha I've confirmed what you said above, it works if a valid `.npmrc` is copied to _all_ function directories - I initially only copied it to the function that required the private package and the problem remained, it seems surprising to me (without the appropriate context) that _all_ functions need to have the `.npmrc` and not just the one that actually uses the private package.

I'll open a `@supabase/cli` issue and reference this, thanks for your assistance.

**Pull request merged**
