### PR TITLE
feat: support setting network permissions via allowNet option

### PR DESCRIPTION
**Pull request by 0x5457**
## What kind of change does this PR introduce?

feature

## What is the new behavior?

Allow network access.  can specify an optional list of IP addresses or hostnames (optionally with ports) to provide an allow-list of allowed network addresses.

```ts
EdgeRuntime.userWorkers.create({
...
  allowNet: ["<IP/HOSTNAME>"]
...
})

```

### CODE REVIEW

**Comment by Code2Life** [comment]
this feature is very useful for fine-grained networking control👍

**Comment by Codexiaoyi** [comment]
also need this feature to me!

**Comment by laktek** [comment]
Can you explain the use cases where you need explicit network access? I guess this would be fine to add for self-hosting, but unlikely we'd provide an option to configure it in hosted environment.

**Comment by 0x5457** [comment]
yes, this is useful for self-hosting cases, especially when EdgeRuntime used standalone rather than with Supabase.

It could extends the EdgeRuntime use case, for example, when the user workers need to be NOT homogeneous, fetching some metadata from localhost is useful, and keep the other network access blocked to avoid security risk.

Another reason is Deno has this option, it would be great if EdgeRuntime could align with Deno
https://docs.deno.com/runtime/manual/basics/permissions/#permissions-list

**Review by nyannyacha — APPROVED** [review]
LGTM!
Thanks for bringing this feature!

cc @laktek

**Comment by laktek** [comment]
Yeah, LGTM too! Thanks @0x5457 for the contribution and @nyannyacha for adding tests.

(This won't be configurable via Supabase CLI or on hosted platform for now. We'll do a separate Changelog announcement when we enable it)

**Comment by krvajal** [comment]
could be possible to add the a deny list as well?

**Pull request merged**
